import type { Metadata } from "next";
import "./globals.css";
import { balooTamma2 } from "../fonts/fonts";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "SSS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${balooTamma2.variable} antialiased max-w-7xl m-auto bg-gray-300 text-black dark:bg-black dark:text-white `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
