import type { Metadata } from "next";
import "./globals.css";
import { balooTamma2 } from "../fonts/fonts";

export const metadata: Metadata = {
  title: "SSS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${balooTamma2.variable} antialiased max-w-7xl m-auto text-black  dark:text-white bg-[radial-gradient(circle_at_bottom_right,_#001e3f_10%,_transparent_80%)] dark:bg-[radial-gradient(circle_at_bottom_right,_#001e3f_30%,_transparent_80%)]`}
      >
        {children}
      </body>
    </html>
  );
}
